HELP: 맞는데 왜 틀린지 모르겠습니다
burning-carrot/study-problem-solving pull request #55
Opened 2020-06-02 14:04 UTC by 2ssue

- X, Y는 좌표로 생각한 변수입니다. 혹시 헷갈릴까봐..

맞왜틀... 도저히 못찾겠습니다. 뭐가 틀렸는지 찾아주세요 😭

2020-06-02 14:13 UTC, Junow requested changes

2020-06-02 14:13 UTC, Junow commented on problems/baekjoon/7576/sujeong.java
> +            for (int i = 0; i < todayRipenTomatoNumber; i++) {
todayRipenTomatoNumber 만큼 반복은 왜 하는건가요?

2020-06-02 14:18 UTC, changicho commented on problems/baekjoon/7576/sujeong.java
> +            for (int i = 0; i < todayRipenTomatoNumber; i++) {
오늘 days 에 익어야 할 토마토만 익히는 것을  반복하기 위해서 같아요

2020-06-02 14:21 UTC, 2ssue commented on problems/baekjoon/7576/sujeong.java
> +            for (int i = 0; i < todayRipenTomatoNumber; i++) {
그 날에 익어있는 토마토 수만큼 반복하기 위해서입니당..

익은 토마토의 좌표를 큐에 넣어서 큐에 있는 토마토 좌표의 상하좌우를 확인해서 익어가게 만들고 있어여

2020-06-02 14:25 UTC, Junow commented on problems/baekjoon/7576/sujeong.java
> +            days += 1;
while 문 한바퀴당 1일씩 증가하려면 현재 queue 에있는 걸 모두 비우면서 순회를 해야하지 않나요? 그러고 다시 큐를 채우고 순회를 하고... 0일차 토마토, 1일차 토마토 이런식으로요

지금 코드에선 토마토를 익힐 수 있는대로 익히고 1일이 증가하기 때문에 실제 익히는 시간과 안맞을 수도 있을것 같습니다 한번 확인해 주세요

2020-06-02 14:30 UTC, Junow requested changes

2020-06-02 14:30 UTC, Junow commented on problems/baekjoon/7576/sujeong.java
> +            for (int i = 0; i < todayRipenTomatoNumber; i++) {
현재 ripenTomatoes 에 있는 토마토들이 오늘의 토마토는 아니지 않나요?? 오늘의 토마토만 꺼낸다고 한다면 n 일차 토마토큐가 따로 있어야할 것 같아요

2020-06-02 14:38 UTC, changicho commented on problems/baekjoon/7576/sujeong.java
> +            days += 1;
각 일마다 토마토를 익히고 다 익었는지 확인하는 로직이라면 이 문구를 while문 최상단으로 올리는 편이 바람직해보입니다.

그리고 큐가 비었는지 다시 확인할 필요가 없고요

2020-06-02 15:30 UTC, 2ssue commented on problems/baekjoon/7576/sujeong.java
> +            for (int i = 0; i < todayRipenTomatoNumber; i++) {
저 while문 라인에 들어왔을 땐 전날에 토마토가 된 신생 토마토들입니다. for문에 들어가게 되면 Queue에 새로운 토마토들이 들어가기 때문에 모든 Queue가 빌 때까지 돌 수가 없어서 이렇게 반복하게 하였습니다.

2020-06-02 15:32 UTC, 2ssue commented on problems/baekjoon/7576/sujeong.java
> +            days += 1;
그렇게 되면 마지막 날에 익은 토마토가 큐에서 빠져나오는 날 까지 계산되어서 이렇게 하게 됐습니다ㅜㅜ

2020-06-03 06:46 UTC, 2ssue commented on problems/baekjoon/7576/sujeong.java
> +        int row = information[2] - '0';
문제는 이곳이었습니다 여려분. 봐주셔서 감사합니다....

테스트케이스는 전부 일의 자리만 입력받아서 통과할 수 있었던 것이고, 일의 자리 이상의 값이 들어오면 대응할 수 없는 코드였어요. 평소엔 `char` 안썼는데 제가 왜 이걸 썼는지 모르겠네여 ☠

2020-06-03 06:47 UTC, closed without merging